# Generated by Django 5.2.16 on 2026-07-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('SHIPPING', 'Logistics'), ('SERVER', 'Hosting/IT'), ('MARKETING', 'Ads/Promo'), ('MISC', 'Other overheads')], max_length=100)),
                ('date_incurred', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StockAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_quantity', models.IntegerField(help_text='Positive for additions, negative for reductions')),
                ('reason', models.CharField(choices=[('RESTOCK', 'Manual Restock Inflow'), ('CORRECTION', 'Inventory Audit Adjustment'), ('DAMAGE', 'Damaged/Loss Write-off')], default='RESTOCK', max_length=20)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, help_text='Wholesale purchase cost', max_digits=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='products.product')),
            ],
        ),
    ]
