# Generated by Django 5.2.16 on 2026-07-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executive_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount sent to the developer', max_digits=12)),
                ('payout_date', models.DateField(help_text='Date the transaction was executed')),
                ('reference_note', models.CharField(blank=True, help_text='e.g. Bank Transfer Ref / EcoCash ID', max_length=255, null=True)),
            ],
        ),
    ]
