# Generated by Django 5.2.16 on 2026-07-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_delivered_orderitem_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False, help_text='Designates if shipment has arrived at consumer address'),
        ),
    ]
