# Generated by Django 5.2.16 on 2026-07-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.PositiveIntegerField(default=0, help_text='Current units ready for deployment'),
        ),
    ]
